variable "COMMON_NAME" { }
variable "ECS_AMI" { }
variable "INSTANCE_TYPE" { }
variable "EC2_INSTANCE_PROFILE_CONTAINER_SERVICE_FOR_EC2_ROLE" { }
variable "EC2_INSTANCE_PROFILE_MANAGED_INSTANCE_CORE" { }
variable "ENVIRONMENT" { }
variable "DESIRED_INSTANCE_COUNT" { }
variable "MIN_INSTANCE_COUNT" { }
variable "MAX_INSTANCE_COUNT" { }
variable "VPC_SUBNET" { }
variable "ASG_ON_DEMAND_CAPACITY" { }
variable "VPC_ID" { }
variable "CLUSTER" { }
variable "EIP_ID" { }
variable "EIP_RESOURCE" { }
variable "EIP_AWS_REGION" { }
variable "LOAD_BALANCER_SG" { }